name: lessonlab
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  provider: ^6.0.0
  protobuf: ^3.1.0
  rinf: ^4.16.3
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+6
  file_selector: ^1.0.1
  flutter_html: ^3.0.0-beta.2
  markdown: ^7.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.0.14
  flutter_quill: ^9.2.2
  htmltopdfwidgets: ^0.0.9
  quill_pdf_converter: ^9.2.2
  quill_html_converter: ^9.2.2
  pdf: ^3.10.7
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/styles/
    - assets/test.md
    - assets/svg/
    - assets/json/
