import 'package:lessonlab/src/global_models/quiz_model.dart';
import 'package:lessonlab/src/lessonlab_modules/quiz/quiz_page/quiz_page_model.dart';

import 'package:lessonlab/messages/quiz/quiz_page.pb.dart'
    // ignore: library_prefixes
    as RinfInterface;
import 'package:rinf/rinf.dart';

class QuizPageConnectionOrchestrator {
  Future<QuizModel> getQuizModel() async {
    final requestMessage = RinfInterface.ReadRequest(req: true);
    final rustRequest = RustRequest(
      resource: RinfInterface.ID,
      operation: RustOperation.Read,
      message: requestMessage.writeToBuffer(),
      // blob: NO BLOB
    );
    final rustResponse = await requestToRust(rustRequest);
    final responseMessage = RinfInterface.ReadResponse.fromBuffer(
      // TODO: fix this null error
      rustResponse.message!,
    );

    return QuizModel.fromAutogenerated(responseMessage.quizModel);
  }
}
