import 'package:lessonlab/src/global_models/quiz_model.dart';
import 'package:lessonlab/messages/quiz/quiz_page.pb.dart'
    // ignore: library_prefixes
    as RinfInterface;

class QuizPageModel {
  late QuizModel quiz;

  QuizPageModel() {
    quiz = QuizModel.initialize();
  }

  QuizPageModel.fromAutogenerated(RinfInterface.QuizModel quizModel) {
    quiz = QuizModel.fromAutogenerated(quizModel);
  }
}

/*

  Model structure

  QuizPageModel {
    QuizModel quiz {
      int id;
      String title;
      List<QuestionModel> questions [
        {
          String question
          List<ChoiceModel> choices = [
            {
              String content;
              bool isCorrect;
              bool isSelected;
            },
            {
              String content;
              bool isCorrect;
              bool isSelected;
            }
          ]
        },
        {
          String question;
          String answer;
        }
      ]

    }
  }

*/
