import 'package:lessonlab/src/global_models/quiz_model.dart';
import 'package:lessonlab/src/lessonlab_modules/quiz/quiz_page/quiz_page_model.dart';

import 'package:lessonlab/messages/quiz/quiz_page.pb.dart'
    // ignore: library_prefixes
    as RinfInterface;
import 'package:rinf/rinf.dart';

import 'dart:developer' as developer;

class QuizPageConnectionOrchestrator {
  Future<QuizModel> getQuizModel() async {
    final requestMessage = RinfInterface.ReadRequest(req: true);
    final rustRequest = RustRequest(
      resource: RinfInterface.ID,
      operation: RustOperation.Read,
      message: requestMessage.writeToBuffer(),
      // blob: NO BLOB
    );
    final rustResponse = await requestToRust(rustRequest);
    final responseMessage = RinfInterface.ReadResponse.fromBuffer(
      // TODO: fix this null error
      rustResponse.message!,
    );

    // LOG QuizModel
    developer.log("id: ${responseMessage.quizModel.id}", name: "quiz model");
    developer.log("title:${responseMessage.quizModel.title}",
        name: "quiz model");
    developer.log("target_path: ${responseMessage.quizModel.targetPath}",
        name: "quiz model");
    developer.log("length: ${responseMessage.quizModel.questions.length}",
        name: "quiz model");
    developer.log(
        "question: ${responseMessage.quizModel.questions[0].question}",
        name: "quiz model");
    developer.log(
        "answer: ${responseMessage.quizModel.questions[0].identification.answer}",
        name: "quiz model");

    return QuizModel.fromAutogenerated(responseMessage.quizModel);
  }
}
