import 'package:lessonlab/messages/quiz/quiz_page.pb.dart'
    // ignore: library_prefixes
    as RinfInterface;

class ChoiceModel {
  late String content;
  late bool isCorrect;
  late bool isSelected;

  ChoiceModel.fromAutogenerated(RinfInterface.ChoiceModel pbChoiceModel) {
    content = pbChoiceModel.content;
    isCorrect = pbChoiceModel.isCorrect;
    isSelected = false;
  }

  void edit() {}
}
