import 'package:lessonlab/messages/entry/menu/menu.pb.dart'
    // ignore: library_prefixes
    as AutogeneratedMenuModel;

class LessonModel {
  late int _id;
  int get id => _id;
  set id(int value) {
    _id = value;
  }

  late Future<String> _title;
  Future<String> get title => _title;
  set title(Future<String> value) {
    _title = value;
  }

  late Future<String> _content;
  Future<String> get content => _content;
  set content(Future<String> value) {
    _content = value;
  }

  late Future<String> _location;
  Future<String> get location => _location;
  set location(Future<String> value) {
    _location = value;
  }

  LessonModel();

  LessonModel.initialize()
      : _id = 0,
        _title = Future.value(''),
        _content = Future.value(''),
        _location = Future.value('');

  LessonModel.fromAutogenerated(
      AutogeneratedMenuModel.LessonModel autogeneratedModel) {
    _id = 0;
    _title = Future.value(autogeneratedModel.title);
    _content = Future.value(autogeneratedModel.content);
    _location = Future.value(autogeneratedModel.location);
  }

  void edit() {}
  void regenerate() {}
  void partialRegenerate() {}
  void appendToLesson() {}
}
