import 'package:lessonlab/messages/entry/menu/menu.pb.dart'
    // ignore: library_prefixes
    as AutogeneratedMenuModel;

class LessonModel {
  late int _id;
  late String _title;
  late String _content;
  late String _location;

  int get id => _id;
  set id(int value) {
    _id = value;
  }

  String get title => _title;
  set title(String value) {
    _title = value;
  }

  String get content => _content;
  set content(String value) {
    _content = value;
  }

  String get location => _location;
  set location(String value) {
    _location = value;
  }

  LessonModel();

  LessonModel.initialize()
      : _id = 0,
        _title = "",
        _content = "",
        _location = "";

  LessonModel.fromAutogenerated(
      AutogeneratedMenuModel.LessonModel autogeneratedModel) {
    _id = autogeneratedModel.id;
    _title = autogeneratedModel.title;
    _content = autogeneratedModel.content;
    _location = autogeneratedModel.location;
  }

  void edit() {}
  void regenerate() {}
  void partialRegenerate() {}
  void appendToLesson() {}
}
