import 'package:lessonlab/src/global_models/question_model.dart';
import 'package:lessonlab/messages/quiz/quiz_page.pb.dart'
    // ignore: library_prefixes
    as RinfInterface;

class QuizModel {
  late int id;
  late String title;
  late int quizType;
  late List<dynamic> questions;

  // Creates a `QuizModel` from auto generated `QuizModel`
  QuizModel.fromAutogenerated(RinfInterface.QuizModel pbQuizModel) {
    id = pbQuizModel.id;
    title = pbQuizModel.title;

    var questions = pbQuizModel.questions.map((pbQuiz) {
      if (pbQuiz.hasIdentification()) {
        return IdentificationQuestionModel.fromAutogenerated(pbQuiz);
      } else if (pbQuiz.hasMultipleChoice()) {
        return MultipleChoiceQuestionModel.fromAutogenerated(pbQuiz);
      }
    }).toList();
  }

  // message
  // u32 id = 1;
  // String title = 2;
  // repeated QuestionModel title = 3;

  void edit() {}
}
